In [112]:
import numpy as np
import pandas as pd

In [137]:
dfTrain = pd.read_excel('Data_train.xlsx')
dfTest = pd.read_excel('Data_test.xlsx')
dfTrain

,Restaurant,Location,Cuisines,Average_Cost,Minimum_Order,Rating,Votes,Reviews,Delivery_Time
0,ID_6321,"FTI College, Law College Road, Pune","Fast Food, Rolls, Burger, Salad, Wraps",₹200,₹50,3.5,12,4,30 minutes
1,ID_2882,"Sector 3, Marathalli","Ice Cream, Desserts",₹100,₹50,3.5,11,4,30 minutes
2,ID_1595,Mumbai Central,"Italian, Street Food, Fast Food",₹150,₹50,3.6,99,30,65 minutes
3,ID_5929,"Sector 1, Noida","Mughlai, North Indian, Chinese",₹250,₹99,3.7,176,95,30 minutes
4,ID_6123,"Rmz Centennial, I Gate, Whitefield","Cafe, Beverages",₹200,₹99,3.2,521,235,65 minutes
...,...,...,...,...,...,...,...,...,...
11089,ID_8067,"BTM Layout 1, Electronic City","Tibetan, Chinese, Continental, Momos",₹250,₹50,4.2,326,189,30 minutes
11090,ID_4620,"Sector 14, Noida",Fast Food,₹100,₹50,3.6,36,16,30 minutes
11091,ID_3392,Majestic,"South Indian, Chinese, North Indian",₹100,₹50,3.5,45,18,30 minutes
11092,ID_4115,"Sector 3, Marathalli",North Indian,₹100,₹50,3.1,24,9,30 minutes
11093,ID_4417,"Sector 63A,Gurgaon",North Indian,₹100,₹50,NEW,-,-,30 minutes

In [138]:
dfTest

,Restaurant,Location,Cuisines,Average_Cost,Minimum_Order,Rating,Votes,Reviews
0,ID_2842,"Mico Layout, Stage 2, BTM Layout,Bangalore","North Indian, Chinese, Assamese",₹350,₹50,4.2,361,225
1,ID_730,"Mico Layout, Stage 2, BTM Layout,Bangalore","Biryani, Kebab",₹100,₹50,NEW,-,-
2,ID_4620,"Sector 1, Noida",Fast Food,₹100,₹50,3.6,36,16
3,ID_5470,"Babarpur, New Delhi, Delhi","Mithai, North Indian, Chinese, Fast Food, Sout...",₹200,₹50,3.6,66,33
4,ID_3249,"Sector 1, Noida","Chinese, Fast Food",₹150,₹50,2.9,38,14
...,...,...,...,...,...,...,...,...
2769,ID_6342,Delhi University-GTB Nagar,"Fast Food, Chinese",₹100,₹50,NEW,-,-
2770,ID_8495,"Mico Layout, Stage 2, BTM Layout,Bangalore","Continental, North Indian, Desserts, Beverages",₹250,₹50,3.1,5,1
2771,ID_7122,"Noorkhan Bazaar, Malakpet, Hyderabad","Andhra, South Indian",₹150,₹50,3.0,16,1
2772,ID_2475,"D-Block, Sector 63, Noida",Bakery,₹100,₹99,3.0,7,2
2773,ID_1595,"Dockyard Road, Mumbai CST Area","Italian, Street Food, Fast Food",₹150,₹50,3.6,99,30

In [139]:
dfTrain['Rating'].replace(to_replace =["NEW","Opening Soon","Temporarily Closed"],
                            value =0,inplace = True)
dfTrain['Rating'].replace(to_replace =["-"],
                            value =-999999,inplace = True)
dfTrain['Rating'] = pd.to_numeric(dfTrain['Rating'])
median = dfTrain.loc[dfTrain['Rating'] > 0, 'Rating'].median()
dfTrain["Rating"] = np.where(dfTrain["Rating"] <= 0, median,dfTrain['Rating'])

In [140]:
dfTest['Rating'].replace(to_replace =["NEW","Opening Soon","Temporarily Closed"],
                            value =0,inplace = True)
dfTest['Rating'].replace(to_replace =["-"],
                            value =-999999,inplace = True)
dfTest['Rating'] = pd.to_numeric(dfTest['Rating'])
median = dfTest.loc[dfTest['Rating'] > 0, 'Rating'].median()
dfTest["Rating"] = np.where(dfTest["Rating"] <= 0, median,dfTest['Rating'])

In [141]:
dfTrain['Votes'].replace(to_replace =["-"],
                            value =-999999,inplace = True)
dfTrain['Votes'] = pd.to_numeric(dfTrain['Votes'])

median = dfTrain.loc[dfTrain['Votes'] > 0, 'Votes'].median()
dfTrain["Votes"] = np.where(dfTrain["Votes"] <= 0, median,dfTrain['Votes'])

In [142]:
dfTest['Votes'].replace(to_replace =["-"],
                            value =-999999,inplace = True)
dfTest['Votes'] = pd.to_numeric(dfTest['Votes'])

median = dfTest.loc[dfTest['Votes'] > 0, 'Votes'].median()
dfTest["Votes"] = np.where(dfTest["Votes"] <= 0, median,dfTest['Votes'])

In [143]:
dfTrain['Reviews'].replace(to_replace =["-"],
                            value =-999999,inplace = True)
dfTrain['Reviews'] = pd.to_numeric(dfTrain['Reviews'])

median = dfTrain.loc[dfTrain['Reviews'] > 0, 'Votes'].median()
dfTrain["Reviews"] = np.where(dfTrain["Reviews"] <= 0, median,dfTrain['Reviews'])

In [144]:
dfTest['Reviews'].replace(to_replace =["-"],
                            value =-999999,inplace = True)
dfTest['Reviews'] = pd.to_numeric(dfTest['Reviews'])

median = dfTest.loc[dfTest['Reviews'] > 0, 'Votes'].median()
dfTest["Reviews"] = np.where(dfTest["Reviews"] <= 0, median,dfTest['Reviews'])

In [145]:
dfTrain['Minimum_Order'] = dfTrain['Minimum_Order'].apply(lambda x:int(x.strip('₹')))
dfTrain['Average_Cost'] = dfTrain['Average_Cost'].apply(lambda x:(x.strip('₹')))
dfTrain['Average_Cost'] = dfTrain['Average_Cost'].apply(lambda x:int(x.replace(',','')) if x != 'for' else -99)
median = int(dfTrain['Average_Cost'].median())
dfTrain["Average_Cost"] = np.where(dfTrain["Average_Cost"] == 0, median,dfTrain['Average_Cost'])

dfTrain['Delivery_Time'] = dfTrain['Delivery_Time'].apply(lambda x:int(x.strip(' minutes')))

In [146]:
dfTest['Minimum_Order'] = dfTest['Minimum_Order'].apply(lambda x:int(x.strip('₹')))
dfTest['Average_Cost'] = dfTest['Average_Cost'].apply(lambda x:(x.strip('₹')))
dfTest['Average_Cost'] = dfTest['Average_Cost'].apply(lambda x:int(x.replace(',','')) if x != 'for' else -99)
median = int(dfTest['Average_Cost'].median())
dfTest["Average_Cost"] = np.where(dfTest["Average_Cost"] == 0, median,dfTest['Average_Cost'])

In [147]:
classifier = KNeighborsClassifier()
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(max_depth=2, random_state=0,n_estimators=100)


def predict(Location,Features):
    
    cuisines = Features.Cuisines
    cuisines = cuisines.split(', ')
    for i,g in dfTrain.groupby('Location'):
        if i == Location:
            relevantFrame = g
    relevantFrame.drop('Location',axis = 1)
    
    relevantFrame['Cuisine_Score'] = relevantFrame['Cuisines'].apply(lambda x:len(set(x.split(', '))&set(cuisines)))
    X = relevantFrame[['Average_Cost','Minimum_Order','Rating','Votes','Reviews','Cuisine_Score']]
    y = relevantFrame['Delivery_Time']
#     Xtest = frameCleanedTesting[['Average_Cost','Minimum_Order','Rating','Votes','Reviews','Cusines']].to_numpy()
    X = X.to_numpy()
    y = y.to_numpy()
    features = Features.values.tolist()
    features.append(len(cuisines))
    features.pop(0)
#     print(features)
    features = np.array(features).reshape(1,-1)
    results = [] #for multiple classifiers
    
    classifier.fit(X,y)
    output = classifier.predict(features)
    reg = LinearRegression().fit(X, y)
    regr.fit(X, y)
    predict = reg.predict(features)
    predictRF = regr.predict(features)
    print(output,predict,predictRF)
#     return output

In [148]:
results = []
print(type(dfTest))
for row in range(len(dfTest)):
    Location = dfTest.loc[row,"Location"]
    features = dfTest.iloc[row, 2:]
    predict(Location,features)
#     print(features)

<class 'pandas.core.frame.DataFrame'>
[30] [37.36222761] [41.07319774]
[30] [33.26015657] [33.17300049]
[30] [35.32752266] [33.8918868]
[30] [32.67973912] [33.40348418]
[30] [35.99484436] [33.8918868]
[30] [34.72765304] [33.8619211]
[30] [40.4903896] [33.45868944]
[30] [33.54648232] [32.91320318]
[30] [34.68007556] [33.8918868]
[30] [36.36296599] [32.85257054]
[30] [36.87577381] [37.04903187]
[30] [34.27078678] [32.85257054]
[30] [36.10157693] [33.8918868]
[45] [42.16401378] [34.48348189]
[30] [28.65511627] [41.12438461]

KeyboardInterrupt: